version: '3.5'
services:
    #
    # H2 Database
    #
    loans-h2:
      image: oscarfonts/h2
      container_name: loans-h2
      ports:
        - "1521:1521"
        - "81:81"
      environment:
        - "WEB_PORT=81"
        - "TCP_PORT=1521"
      command:
        bash -c "java -cp /opt/h2/bin/h2*.jar org.h2.tools.Server -web -webAllowOthers -webPort $${WEB_PORT} -tcp -tcpAllowOthers -tcpPort $${TCP_PORT} -baseDir $${DATA_DIR}"
    #
    # Loans service A
    #
    loans-node-A:
      container_name: loans-node-A
      image: loans-node:latest
      ports:
        - "8085:8085"
      environment:
        - "server.port=8085"
        - "spring.profiles.active=cluster"
        - "micro-service.instance-name=LoansNodeA"
        - "EUREKA_URI_A=http://service-registry-a:8761/eureka"
        - "EUREKA_URI_B=http://service-registry-b:8762/eureka"

    #
    # Loans service B
    #
    loans-node-B:
      container_name: loans-node-B
      image: loans-node:latest
      ports:
        - "8086:8086"
      environment:
        - "server.port=8086"
        - "spring.profiles.active=cluster"
        - "micro-service.instance-name=LoansNodeB"
        - "EUREKA_URI_A=http://service-registry-a:8761/eureka"
        - "EUREKA_URI_B=http://service-registry-b:8762/eureka"


networks:
  default:
    external:
      name: microservices_network