version: '3.5'
services:
    #
    # Service registry
    #
    service-registry:
        container_name: service-registry
        image: service-registry:latest
        ports:
          - "8761:8761"
        environment:
          - "server.port=8761"
    #
    # Zuul server
    #
    zuul-server:
        container_name: zuul-server
        image: zuul-server:latest
        ports:
          - "8080:8080"
        environment:
          - "EUREKA_URI=http://service-registry:8761/eureka"

networks:
  default:
    name: microservices_network