---
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
server:
  port: 8080
spring:
  application:
    name: zuul-server
zuul:
  routes:
    loans:
      path: /loans/**
      serviceId: loans-node
      stripPrefix: false
      retryable: true
    process:
      path: /process/**
      serviceId: process-node
      stripPrefix: false
      retryable: true
  ignored-services: '*'
