---
server:
  port: 8761
spring:
  application:
    name: service-registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 5

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

---
spring:
  profiles:
    active: cluster

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${REPLICA_URI}