spring:
  application:
    name: process-node
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
server:
  port: 8090
  servlet:
    context-path: /process-node
ribbon:
  ServerListRefreshInterval: 5
  eager-load:
    enabled: true
    clients: loans-node

---
spring:
  profiles: cluster
  datasource:
    url: jdbc:h2:tcp://process-h2:1522/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI_A:http://localhost:8761/eureka}, ${EUREKA_URI_B:http://localhost:8762/eureka}